# Generated by Django 3.2.8 on 2021-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tegs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
